services:
  - type: web
    name: simo-gateway-poc
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20"
